//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RS.DataAccessLayer.entitydata
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RSEntities : DbContext
    {
        public RSEntities()
            : base("name=RSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<RS_Album> RS_Album { get; set; }
        public virtual DbSet<RS_ContactUs> RS_ContactUs { get; set; }
        public virtual DbSet<RS_Country> RS_Country { get; set; }
        public virtual DbSet<RS_District> RS_District { get; set; }
        public virtual DbSet<RS_EventType> RS_EventType { get; set; }
        public virtual DbSet<RS_Gallary> RS_Gallary { get; set; }
        public virtual DbSet<RS_Location> RS_Location { get; set; }
        public virtual DbSet<RS_NewsType> RS_NewsType { get; set; }
        public virtual DbSet<RS_Role> RS_Role { get; set; }
        public virtual DbSet<RS_State> RS_State { get; set; }
        public virtual DbSet<RS_UserDetail> RS_UserDetail { get; set; }
        public virtual DbSet<RS_RathoreDetails> RS_RathoreDetails { get; set; }
        public virtual DbSet<RS_Event> RS_Event { get; set; }
        public virtual DbSet<RS_News> RS_News { get; set; }
    }
}
