//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RS.DataAccessLayer.entitydata
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_Gallary
    {
        public int PhotoId { get; set; }
        public Nullable<int> AlbumId { get; set; }
        public string PhotoLink { get; set; }
        public Nullable<System.DateTime> PostedOn { get; set; }
        public string Location { get; set; }
        public string PhotoDescription { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsCoverPhoto { get; set; }
        public Nullable<int> Likes { get; set; }
    }
}
