//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RS.DataAccessLayer.entitydata
{
    using System;
    using System.Collections.Generic;
    
    public partial class RS_RathoreDetails
    {
        public int RathoreDetailId { get; set; }
        public string Name { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public Nullable<int> FatherNameId { get; set; }
        public Nullable<int> MotherNameId { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string PhoneNumber { get; set; }
        public string Occupation { get; set; }
        public bool IsMarried { get; set; }
        public string SpouseName { get; set; }
        public Nullable<int> SpouseNameId { get; set; }
        public Nullable<int> CurrentCountry { get; set; }
        public Nullable<int> CurrentState { get; set; }
        public Nullable<int> CurrentDistrict { get; set; }
        public Nullable<int> CurrentLocation { get; set; }
        public string CurrentAddress { get; set; }
        public Nullable<int> NativeCountry { get; set; }
        public Nullable<int> NativeState { get; set; }
        public Nullable<int> NativeDistrict { get; set; }
        public Nullable<int> NativeLocation { get; set; }
        public string NativeAddress { get; set; }
        public string EmailId { get; set; }
        public string FinalEducation { get; set; }
        public Nullable<int> NoOfChildern { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<int> LoginCount { get; set; }
        public Nullable<int> Role { get; set; }
        public string gender { get; set; }
    }
}
